function darkTheme(){
    document.querySelector('.para-of-first-parallax').style.backgroundColor = "black"
    document.querySelector('.para-of-first-parallax').style.color = "white"
    document.querySelector('.para-of-second-parallax').style.backgroundColor = "black"
    document.querySelector('.para-of-second-parallax').style.color = "white"
    document.querySelector('.para-of-third-parallax').style.backgroundColor = "black"
    document.querySelector('.para-of-third-parallax').style.color = "white"
    document.querySelector('.name-heading').style.backgroundColor = "black"
    document.querySelector('.name-heading').style.color = "white"
    document.querySelector('.project-heading').style.backgroundColor = "black"
    document.querySelector('.project-heading').style.color = "white"
    document.querySelector('.achievement-heading').style.backgroundColor = "black"
    document.querySelector('.achievement-heading').style.color = "white"
    document.querySelector('#dark-theme').style.backgroundColor = "black"
    document.querySelector('#dark-theme').style.color = "white"
    document.querySelector('#light-theme').style.backgroundColor = "black"
    document.querySelector('#light-theme').style.color = "white"
}
function lightTheme(){
    document.querySelector('.para-of-first-parallax').style.backgroundColor = "white"
    document.querySelector('.para-of-first-parallax').style.color = "black"
    document.querySelector('.para-of-second-parallax').style.backgroundColor = "white"
    document.querySelector('.para-of-second-parallax').style.color = "black"
    document.querySelector('.para-of-third-parallax').style.backgroundColor = "white"
    document.querySelector('.para-of-third-parallax').style.color = "black"
    document.querySelector('.name-heading').style.backgroundColor = "white"
    document.querySelector('.name-heading').style.color = "black"
    document.querySelector('.project-heading').style.backgroundColor = "white"
    document.querySelector('.project-heading').style.color = "black"
    document.querySelector('.achievement-heading').style.backgroundColor = "white"
    document.querySelector('.achievement-heading').style.color = "black"
    document.querySelector('#light-theme').style.backgroundColor = "white"
    document.querySelector('#light-theme').style.color = "black"
    document.querySelector('#dark-theme').style.backgroundColor = "white"
    document.querySelector('#dark-theme').style.color = "black"
}